-- MySQL Script generated by MySQL Workbench
-- 09/09/15 17:56:28
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Empresa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Empresa` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Nombre` VARCHAR(100) NOT NULL COMMENT '',
  `Habilitado` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `idEmpresa_UNIQUE` (`ID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Gerencia`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Gerencia` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_Empresa` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(100) NOT NULL COMMENT '',
  `Habilitado` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `idGerencia_UNIQUE` (`ID` ASC)  COMMENT '',
  INDEX `fk_Gerencia_Empresa_idx` (`ID_Empresa` ASC)  COMMENT '',
  CONSTRAINT `fk_Gerencia_Empresa`
    FOREIGN KEY (`ID_Empresa`)
    REFERENCES `mydb`.`Empresa` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Sede`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Sede` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_Empresa` INT NOT NULL COMMENT '',
  `Nombre` VARCHAR(100) NOT NULL COMMENT '',
  `Habilitado` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '',
  INDEX `fk_Sede_Empresa1_idx` (`ID_Empresa` ASC)  COMMENT '',
  CONSTRAINT `fk_Sede_Empresa1`
    FOREIGN KEY (`ID_Empresa`)
    REFERENCES `mydb`.`Empresa` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Usuario` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_Gerencia` INT NULL COMMENT '',
  `ID_Sede` INT NULL COMMENT '',
  `DNI` VARCHAR(45) NOT NULL COMMENT '',
  `Nombre` VARCHAR(100) NOT NULL COMMENT '',
  `Contrasena` VARCHAR(300) NOT NULL COMMENT 'Vamos a usar la función password_hash de PHP para manejar las contraseñas: http://php.net/manual/en/function.password-hash.php',
  `Mail` VARCHAR(100) NOT NULL COMMENT '',
  `Puntaje` INT NOT NULL COMMENT '',
  `Habilitado` TINYINT(1) NOT NULL COMMENT '',
  `ContrasenaNueva` VARCHAR(300) NULL COMMENT '',
  `CodigoVerificacion` VARCHAR(300) NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '',
  INDEX `fk_Usuario_Gerencia1_idx` (`ID_Gerencia` ASC)  COMMENT '',
  INDEX `fk_Usuario_Sede1_idx` (`ID_Sede` ASC)  COMMENT '',
  UNIQUE INDEX `DNI_UNIQUE` (`DNI` ASC)  COMMENT '',
  UNIQUE INDEX `Mail_UNIQUE` (`Mail` ASC)  COMMENT '',
  UNIQUE INDEX `Nombre_UNIQUE` (`Nombre` ASC)  COMMENT '',
  CONSTRAINT `fk_Usuario_Gerencia1`
    FOREIGN KEY (`ID_Gerencia`)
    REFERENCES `mydb`.`Gerencia` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Usuario_Sede1`
    FOREIGN KEY (`ID_Sede`)
    REFERENCES `mydb`.`Sede` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Nivel`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Nivel` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Puntaje` INT NOT NULL COMMENT '',
  `Texto` VARCHAR(45) NOT NULL COMMENT '',
  `Orden` INT NOT NULL COMMENT '',
  `Habilitado` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pregunta` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_Nivel` INT NOT NULL COMMENT '',
  `Texto` VARCHAR(3000) NOT NULL COMMENT '',
  `Habilitado` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '',
  INDEX `fk_Pregunta_Nivel1_idx` (`ID_Nivel` ASC)  COMMENT '',
  CONSTRAINT `fk_Pregunta_Nivel1`
    FOREIGN KEY (`ID_Nivel`)
    REFERENCES `mydb`.`Nivel` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Respuesta` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_Pregunta` INT NOT NULL COMMENT '',
  `Texto` VARCHAR(3000) NOT NULL COMMENT '',
  `Correcta` TINYINT(1) NOT NULL COMMENT '',
  `Habilitado` TINYINT(1) NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '',
  INDEX `fk_Respuesta_Pregunta1_idx` (`ID_Pregunta` ASC)  COMMENT '',
  CONSTRAINT `fk_Respuesta_Pregunta1`
    FOREIGN KEY (`ID_Pregunta`)
    REFERENCES `mydb`.`Pregunta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Partida`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Partida` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `Habilitado` TINYINT(1) NOT NULL COMMENT '',
  `Fecha_Inicio` DATETIME NOT NULL COMMENT '',
  `Fecha_Fin` DATETIME NULL COMMENT '',
  `Cantidad_Usuario` INT NOT NULL COMMENT '',
  `Cantidad_Preguntas` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '')
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Partida_Usuario`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Partida_Usuario` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_Partida` INT NOT NULL COMMENT '',
  `ID_Usuario` INT NOT NULL COMMENT '',
  `Fecha_Inicio` DATETIME NOT NULL COMMENT '',
  `Fecha_Fin` DATETIME NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '',
  INDEX `fk_Partida_Usuario_Partida1_idx` (`ID_Partida` ASC)  COMMENT '',
  INDEX `fk_Partida_Usuario_Usuario1_idx` (`ID_Usuario` ASC)  COMMENT '',
  CONSTRAINT `fk_Partida_Usuario_Partida1`
    FOREIGN KEY (`ID_Partida`)
    REFERENCES `mydb`.`Partida` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Usuario_Usuario1`
    FOREIGN KEY (`ID_Usuario`)
    REFERENCES `mydb`.`Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Partida_Pregunta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Partida_Pregunta` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_Partida` INT NOT NULL COMMENT '',
  `ID_Pregunta` INT NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  INDEX `fk_Partida_Pregunta_Partida1_idx` (`ID_Partida` ASC)  COMMENT '',
  INDEX `fk_Partida_Pregunta_Pregunta1_idx` (`ID_Pregunta` ASC)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '',
  CONSTRAINT `fk_Partida_Pregunta_Partida1`
    FOREIGN KEY (`ID_Partida`)
    REFERENCES `mydb`.`Partida` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Pregunta_Pregunta1`
    FOREIGN KEY (`ID_Pregunta`)
    REFERENCES `mydb`.`Pregunta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Partida_Respuesta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Partida_Respuesta` (
  `ID` INT NOT NULL AUTO_INCREMENT COMMENT '',
  `ID_Partida_Pregunta` INT NOT NULL COMMENT '',
  `ID_Partida_Usuario` INT NOT NULL COMMENT '',
  `ID_Respuesta` INT NOT NULL COMMENT '',
  `Fecha_Respuesta` DATETIME NOT NULL COMMENT '',
  PRIMARY KEY (`ID`)  COMMENT '',
  UNIQUE INDEX `ID_UNIQUE` (`ID` ASC)  COMMENT '',
  INDEX `fk_Partida_Respuesta_Partida_Pregunta1_idx` (`ID_Partida_Pregunta` ASC)  COMMENT '',
  INDEX `fk_Partida_Respuesta_Partida_Usuario1_idx` (`ID_Partida_Usuario` ASC)  COMMENT '',
  INDEX `fk_Partida_Respuesta_Respuesta1_idx` (`ID_Respuesta` ASC)  COMMENT '',
  CONSTRAINT `fk_Partida_Respuesta_Partida_Pregunta1`
    FOREIGN KEY (`ID_Partida_Pregunta`)
    REFERENCES `mydb`.`Partida_Pregunta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Respuesta_Partida_Usuario1`
    FOREIGN KEY (`ID_Partida_Usuario`)
    REFERENCES `mydb`.`Partida_Usuario` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Partida_Respuesta_Respuesta1`
    FOREIGN KEY (`ID_Respuesta`)
    REFERENCES `mydb`.`Respuesta` (`ID`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
